crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('follow_up/', include('follow_up.urls')),
    path('qoutes/', include('qoutes.urls')),
    path('organizations/', include('organizations.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

crm/qoutes/urls.py
from django.urls import include, path
from rest_framework import routers
from qoutes.views import (
    create_qoutes_view,
    list_qoutes_view,
    send_email_view,
    pdf_view
)
from qoutes.api import (
    QouteViewSet,
    QouteProductDetailViewSet,
)

app_name = "qoutes"

router = routers.DefaultRouter()
router.register(r'qoute', QouteViewSet, basename='Qoute')
router.register(r'product', QouteProductDetailViewSet, basename='QouteProductDetail')

urlpatterns = [
    path('api/', include(router.urls)),
    path('create/', create_qoutes_view, name='create-qoutes'),
    path('list/', list_qoutes_view, name='list-qoutes'),
    path('send_email/<int:pk>', send_email_view, name='send-email'),
    path('pdf/<int:pk>', pdf_view, name='pdf'),
]

crm/qoutes/models.py
from enum import unique
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Qoute(models.Model):
    create_date = models.DateField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))
    creator = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name=_('کارشناس فروش'))
    organization = models.ForeignKey('organizations.Organization', on_delete=models.PROTECT, verbose_name=_('ارگان'))


    class Meta:
        ordering = ('create_date',)
        verbose_name = _('پیش فاکتور')
        verbose_name_plural = _('پیش فاکتور ها')

    def __str__(self):
        return str(self.organization) + " _ " + str(self.creator)

    def get_total_products_price(self):
        total_products_price = 0
        
        for prod in self.qouteproductdetail_set.all():
            total_products_price += prod.calculate_total_price()

        return total_products_price

    def get_total_qty(self):
        total_qty = 0
        
        for prod in self.qouteproductdetail_set.all():
            total_qty += prod.qty

        return total_qty


class QouteProductDetail(models.Model):
    product = models.ForeignKey('products.Product', on_delete=models.PROTECT, verbose_name=_('محصول'))
    qty = models.PositiveIntegerField(verbose_name=_('تعداد'))
    price = models.PositiveIntegerField(verbose_name=_('قیمت'))
    discount_percent = models.PositiveIntegerField(verbose_name=_('درصد تخفیف'))
    qoute = models.ForeignKey(Qoute, on_delete=models.PROTECT, verbose_name=_('پیش فاکتور'))

    class Meta:
        ordering = ('price',)
        verbose_name = _('جزئیات محصول پیش فاکتور')
        verbose_name_plural = _('جزئیات محصولات پیش فاکتور')

    def __str__(self):
        return str(self.qoute) + " _ " + str(self.product)

    def calculate_total_price(self):
        total_price = self.price * self.qty
        total_price -= total_price * (self.discount_percent / 100)
        
        if self.product.includes_taxes:
            total_price += total_price / 10

        return total_price

email_status_choise = [
    ['شکست', 'ارسال ایمیل شکست خورد.'], 
    ['موفقیت', 'ارسال ایمیل موفقیت امیز بود.']
]

class Emails(models.Model):
    reciver = models.CharField(max_length=50, verbose_name='ایمیل دریافت کننده')
    status = models.CharField(max_length=6, verbose_name="وضعیت ارسال", choices=email_status_choise)
    send_date = models.DateField(verbose_name="تاریخ ارسال ایمیل", auto_now_add=True)
    sender = models.ForeignKey('auth.user', on_delete=models.CASCADE, verbose_name='کاربر ارسال کننده')
    class Meta:
        ordering = ('send_date',)
        verbose_name = _('ایمیل')
        verbose_name_plural = _('ایمیل ها')

    def __str__(self):
        return str(self.reciver) + " _ " + str(self.sender.username)

crm/qoutes/forms.py
from django import forms

from qoutes import models


class QoutesForm(forms.ModelForm):
    """
        A model form for Qoute model
    """
    
    class Meta:
        model = models.Qoute
        fields = [
            'creator',
            'organization',
        ]


class QouteProductDetailForm(forms.ModelForm):
    """
        A model form for QouteProductDetail model
    """
    
    qoute = forms.IntegerField()

    class Meta:
        model = models.QouteProductDetail
        fields = [
            'product',
            'qty',
            'price',
            'discount_percent',
        ]

crm/qoutes/views.py
import os

import weasyprint
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import mail
from django.http import HttpResponse
from django.shortcuts import redirect, render

from qoutes.forms import QouteProductDetailForm, QoutesForm
from qoutes.models import Emails, Qoute, QouteProductDetail


def get_pdf(request, pk):
    """
        Get qoute detail based on pk and return a pdf.
    """

    qoute = Qoute.objects.get(pk=pk)

    rendred_html = render(request, 'qoutes/qoutes_info.html', {
        'qoute':qoute,
        'qouteProducts':QouteProductDetail.objects.filter(qoute=qoute)
    })

    pdf = weasyprint.HTML(string=rendred_html.content).write_pdf()
    return pdf


@login_required
def send_email_view(request, pk):
    """
        Gets a pk and make qoute pdf from that pk
        then returns a redirect to qoute list.
    """

    pdf = get_pdf(request, pk)
    reciver = os.environ.get('EMAIL_HOST_USER')
    # response = HttpResponse(pdf, content_type='application/pdf')
    email = mail.EmailMessage(
        subject='پیش فاکتور',
        from_email=os.environ.get('EMAIL_HOST_USER'),
        body="پیش فاکتور محصولات",
        to=[reciver]
    )
    
    email.attach("qoute.pdf", pdf, 'application/pdf')
    email.send()

    email_inst = Emails(reciver=reciver, status='موفقیت', sender=request.user)
    email_inst.save()

    messages.success(request, 'Successfully sent email.')
    return redirect('qoutes:list-qoutes')


@login_required
def pdf_view(request, pk):
    """
        Makes the pdf and send HttpResponse
    """

    pdf = get_pdf(request, pk)

    response = HttpResponse(pdf, content_type='application/pdf')
    return response


@login_required
def create_qoutes_view(request):
    """
        Return a html contains qoute creation form 
    """

    form_instance = QoutesForm()
    product_form = QouteProductDetailForm() 

    return render(request, 'qoutes/qoutes_form.html', {
        'form': form_instance,
        'product_form': product_form,
        'page_title': 'Create a qoute',
        'form_method': 'POST',
        'form_action': '/qoutes/api/qoute/',
        'product_form_action': '/qoutes/api/product/',
        'reset_form': True,
        'success_message': 'successfuly created qoutes.',
        'product_error_message': 'adding product failed.',
    })


@login_required
def list_qoutes_view(request):
    """
        Returns a html with a empty table to filled by ajax.
    """

    return render(request, 'qoutes/qoutes_list.html', {
        'page_title': 'qoutes list'
    })

crm/qoutes/templates/qoutes/qoutes_form.html
{% extends 'web/base.html' %}
{% load widget_tweaks %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-8">
        <h3>{{ page_title }}</h3>
        <form id="qoutesForm" method="{{ form_method }}" enctype="multipart/form-data" action="{{ form_action }}">
            {% csrf_token %}
            <div class="form-group">
                {% render_field form.creator class="form-control" placeholder=form.creator.label %}
            </div>
            
            <div class="form-group">
                {% render_field form.organization class="form-control" placeholder=form.organization.label %}
            </div>
           
        </form>
        <div id="productsForms">
        </div>
        <div class="row justify-content-between">
            <button id="submitButton" class="btn btn-primary"> Save</button>
            <button id="addButton" class="btn btn-primary">ADD</button>
        </div>
    </div>
    <div id="productFormTemple" hidden>
        <form class="productForm" method="{{ form_method }}" enctype="multipart/form-data" action="{{ product_form_action }}">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-3">
                    {% render_field product_form.discount_percent class="form-control" placeholder=product_form.discount_percent.label %}
                </div>
                <div class="form-group col-3">
                    {% render_field product_form.price class="form-control" placeholder=product_form.price.label %}
                </div>
                <div class="form-group col-2">
                    {% render_field product_form.qty class="form-control" placeholder=product_form.qty.label %}
                </div>
                <div class="form-group col-3">
                    {% render_field product_form.product class="form-control" placeholder=product_form.product.label %}
                </div>
                <div hidden>
                    {% render_field product_form.qoute %}
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="$(this).parent().parent().remove()">
                    &times;
                </button>
            </div>
        </form>
    </div>
    <script>
        var qoute_pk = 1;

        $( document ).ready(function() {
            $('#productsForms').append($("#productFormTemple .productForm").clone())
        });
        $('button#addButton').click( function() {
            $('#productsForms').append($("#productFormTemple .productForm").clone())
        })
        $('button#submitButton').click( function() {

            var form = $('form#qoutesForm');
            var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');

            $.ajax({
                type: form.attr('method'),
                url: form.attr('action'),
                data: form.serialize(),
                headers:{"X-CSRFToken": $crf_token},
                error: 
                    function(data) {
                        alert(data['responseText'])
                        console.log(data)

                    },
                success: 
                    function(data) {
                        console.log("Added Qoute")

                        qoute_pk = data['pk']
                        $('.productForm #id_qoute').val(qoute_pk)
                        var success_message = 
                            `<div class="alert alert-success alert-dismissible">
                                {{ success_message }}
                                <button type="button" data-dismiss="alert" class="close">&times;</button>
                            </div>`
                        if (form.attr('method') == "POST" ) {
                            $('form#qoutesForm')[0].reset();
                            console.log("CLEAR PRODUCTS")
                        }
                        $('#messages').append(success_message)
                        
                        send_products()
                    },
            });
            
            function send_products() {
                console.log("Sent Products")
                $('#productsForms form').each(function(index, value) {
                    var product_form = $(this);

                    $.ajax({
                        type: product_form.attr('method'),
                        url: product_form.attr('action'),
                        data: product_form.serialize(),
                        headers:{"X-CSRFToken": $crf_token},
                        error: 
                            function(data) {
                                alert(data['responseText'])
                                console.log(data)
                                var success_message = 
                                    `<div class="alert alert-danger alert-dismissible">
                                        {{ product_error_message }}
                                        <button type="button" data-dismiss="alert" class="close">&times;</button>
                                    </div>`
                                $('#messages').append(success_message)
                                
                            },
                        success: 
                            function(data) {
                                console.log(`ADDED product:> ${index}: ${this.id}`)                           
                            },
                    });

                });
            }
           

        });
    </script>
{% endblock %}

crm/qoutes/templates/qoutes/qoutes_info.html
<dl>
    <dt>نام ارگان</dt>
    <dd>{{ qoute.organization.name }}</dd>
    <dt>کارشناس فروش</dt>
    <dd>{{ qoute.creator.username }}</dd>
</dl>
<table>
    <thead>
    <tr>
        <th>ردیف</th>
        <th>نام کالا</th>
        <th>تعداد</th>
        <th>قیمت</th>
        <th>تخفیف</th>
        <th>جمع</th>
    </tr>
    </thead>
    <tbody>
    {% for qouteProduct in qouteProducts %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ qouteProduct.prodcut.name }}</td>
            <td>{{ qouteProduct.qty }}</td>
            <td>{{ qouteProduct.price }} ریال</td>
            <td>{{ qouteProduct.discount_percent }}</td>
            <td>{{ qouteProduct.calculate_total_price }} ریال</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3">
            {{ qoute.get_total_qty }}
        </td>
        <td colspan="2">
            مبلغ قابل پرداخت:
            {{ qoute.get_total_products_price }}
            ریال
        </td>
    </tr>
    </tfoot>
</table>

crm/qoutes/templates/qoutes/qoutes_list.html
{% extends 'web/base.html' %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-8">
        <h3>{{ page_title }}</h3>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">نام مشتری</th>
                <th scope="col">دستگاه ها</th>
                <th scope="col">مبلغ نهایی</th>
                <th scope="col">PDF</th>
                <th scope="col">عملیات</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
    </div>
    <script>

        $( document ).ready(function() {
            $.ajax({
                url: "http://127.0.0.1:8000/qoutes/api/qoute",
                headers: {
                    "Accept":"application/json"
                },
                error: 
                    function(data) {
                        alert("ERROR")
                        console.log(data)
                    },
                success: 
                    update_table,
            });
        });
        function update_table(data) {
            console.log(data)
            for (const qoutes_index in data['results']) {
                var qoute = data['results'][qoutes_index]
                
                var row = 
                `<tr>
                    <th scope="row">${Number(qoutes_index)+1}</th>
                    <td>${qoute['organization_name']}</td>
                    <td>${qoute['products_text']}</td>
                    <td>${qoute['total_products_price']}</td>
                    <td><a href="http://127.0.0.1:8000/qoutes/pdf/${qoute['pk']}"> 
                        <i class="fa fa-download"></i>
                    </a></td>
                    <td><a href="http://127.0.0.1:8000/qoutes/send_email/${qoute['pk']}"> ارسال ایمیل با ایمیل </a></td>
                </tr>`
                $("tbody").append(row)
            }
        }
    </script>
{% endblock %}