crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('follow_up/', include('follow_up.urls')),
    path('qoutes/', include('qoutes.urls')),
    path('organizations/', include('organizations.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

crm/follow_up/urls.py
from django.urls import include, path
from rest_framework import routers
from follow_up.views import (
    create_follow_ups_view,
    list_follow_ups_view,
)
from follow_up.api import FollowUpViewSet

app_name = "follow_up"

router = routers.DefaultRouter()
router.register(r'', FollowUpViewSet, basename='FollowUp')

urlpatterns = [
    path('api/', include(router.urls)),
    path('create/', create_follow_ups_view, name='create-follow-up'),
    path('list/', list_follow_ups_view, name='list-follow-ups'),
]

crm/organizations/urls.py
from django.urls import include, path
from rest_framework import routers
from organizations import api

router = routers.DefaultRouter()
router.register(r'api', api.OrganizationsViewSet, basename='Organization')

urlpatterns = [
    path('', include(router.urls)),
]

crm/qoutes/urls.py
from django.urls import include, path
from rest_framework import routers
from qoutes.views import (
    create_qoutes_view,
    list_qoutes_view,
    send_email_view,
    pdf_view
)
from qoutes.api import (
    QouteViewSet,
    QouteProductDetailViewSet,
)

app_name = "qoutes"

router = routers.DefaultRouter()
router.register(r'qoute', QouteViewSet, basename='Qoute')
router.register(r'product', QouteProductDetailViewSet, basename='QouteProductDetail')

urlpatterns = [
    path('api/', include(router.urls)),
    path('create/', create_qoutes_view, name='create-qoutes'),
    path('list/', list_qoutes_view, name='list-qoutes'),
    path('send_email/<int:pk>', send_email_view, name='send-email'),
    path('pdf/<int:pk>', pdf_view, name='pdf'),
]

crm/web/urls.py
from django.urls import path
from web.views import create_organizations_view, home, list_organizations_view, retrieve_organizations_view, edit_organizations_view

app_name = 'web'

urlpatterns = [
    path('organizations/create/', create_organizations_view, name='create-organizations'),
    path('organizations/list/', list_organizations_view, name='list-organizations'),
    path('organizations/retrieve/<int:pk>/', retrieve_organizations_view, name='retrieve-organizations'),
    path('organizations/edit/<int:pk>/', edit_organizations_view, name='edit-organizations'),
    path('', home, name='home'),
]

crm/organizations/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

        
class OrganizationProduct(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('محصول مشتری'))
    related_products = models.ManyToManyField('products.Product', verbose_name=_('محصولات مرتبط'))

    class Meta:
        ordering = ('name',)
        verbose_name = _('محصول ارگان')
        verbose_name_plural = _('محصولات ارگان')

    def __str__(self):
        return self.name

        
class Organization(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_('نام'))
    province = models.CharField(max_length=50, verbose_name=_('استان'))
    phone_number = models.CharField(max_length=20, unique=True, verbose_name=_('شماره تلفن'))
    workers_count = models.PositiveIntegerField(verbose_name=_('تعداد کارگران'))
    contact_fullname = models.CharField(max_length=50, verbose_name=_('نام مخاطب'))
    contact_phone_number = models.CharField(max_length=20, verbose_name=_('شماره تلفن مخاطب'))
    email = models.EmailField(unique=True, verbose_name=_('ایمیل'))
    create_date = models.DateField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))
    registrar = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name=_('کارشناس فروش'))
    products = models.ManyToManyField(OrganizationProduct, verbose_name=_('محصولات'))

    class Meta:
        ordering = ('name',)
        verbose_name = _('ارگان')
        verbose_name_plural = _('ارگان ها')

    def __str__(self):
        return self.name


class Opportunity(models.Model):
    create_date = models.DateField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))
    last_modified_date = models.DateField(auto_now=True, verbose_name=_('تاریخ آخرین پیگیری'))
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name=_('ارگان طرف حساب'))
    sales_people = models.ManyToManyField('auth.user', verbose_name=_('کارشناسان فروش'))
    # status
    class Meta:
        ordering = ('last_modified_date',)
        verbose_name = _('موقعیت')
        verbose_name_plural = _('موقعیت ها')

    def __str__(self):
        return str(self.organization) + " _ " + str(self.sales_people)


class Report(models.Model):
    text = models.TextField(verbose_name=_('گزارش کار'))
    create_date = models.DateField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))
    creator = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name=_('کارشناس فروش'))
    opportunity = models.ForeignKey(Opportunity, on_delete=models.PROTECT, verbose_name=_('موقعیت فروش'))

    class Meta:
        ordering = ('create_date',)
        verbose_name = _('گزارش')
        verbose_name_plural = _('گزارش ها')

    def __str__(self):
        return str(self.opportunity) + " _ " + str(self.creator)

crm/web/templates/web/base.html
{% load static %}
{% load i18n %}


<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script
			  src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/d6f5904bef.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <title>
        CRM:
        {% block page_header_title %}
            {{ page_title }}
        {% endblock %}
    </title>
</head>
<body>
<div class="container">
   
    <div class="row mt-3 mb-3">
        <div class="col-12" id="messages">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible">
                        {{ message }}
                        <button type="button" data-dismiss="alert" class="close">&times;</button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
  
    <!-- <div class="card card-body">
        
    </div> -->

 

    <div class="row mb-4 mt-4">
        <div class="col-4">
            <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                  <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
                  <span class="fs-4">CRM</span>
                </a>
                <hr>
                <ul class="nav nav-pills flex-column mb-auto">
                  <li>
                    <a class="btn" data-toggle="collapse" href="#organizationsCollapse" role="button" aria-expanded="false" aria-controls="organizationsCollapse">
                      Organizations
                    </a>
                    <div class="collapse" id="organizationsCollapse">
                      <a href="{% url 'web:create-organizations'%}" class="nav-link link-dark">
                        Create organization
                      </a>
                      <a href="{% url 'web:list-organizations'%}" class="nav-link link-dark">
                        List organizationss
                      </a>
                    </div>
                  </li>
                  <li>
                    <a class="btn" data-toggle="collapse" href="#qoutesCollapse" role="button" aria-expanded="false" aria-controls="qoutesCollapse">
                      Qoutes
                    </a>
                    <div class="collapse" id="qoutesCollapse">
                      <a href="{% url 'qoutes:create-qoutes'%}" class="nav-link link-dark">
                        Create qoute
                      </a>
                      <a href="{% url 'qoutes:list-qoutes'%}" class="nav-link link-dark">
                        List qoutes
                      </a>
                    </div>
                  </li>
                  <li>
                    <a class="btn" data-toggle="collapse" href="#follow_upsCollapse" role="button" aria-expanded="false" aria-controls="qoutesCollapse">
                      Follow Ups
                    </a>
                    <div class="collapse" id="follow_upsCollapse">
                      <a href="{% url 'follow_up:create-follow-up'%}" class="nav-link link-dark">
                        Create follow up
                      </a>
                      <a href="{% url 'follow_up:list-follow-ups'%}" class="nav-link link-dark">
                        List follow ups
                      </a>
                    </div>
                  </li>
                <hr>
                <hr>

                  <li>
                      {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="nav-link link-dark">LOGOUT</a>
                      {%else%}
                        <a href="{% url 'login' %}" class="nav-link link-dark">LOGIN</a>
                      {% endif %}
                  </li>
                  
                </ul>
                
              </div>

              <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <select class="form-select form-select-dark" name="language" onchange="this.form.submit()">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
              </form>
        </div>
        <div class="b-example-divider"></div>
        {% block content %}YOUR CONTENT GOES HERE{% endblock %}
    </div>
</div>
<!-- <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->



{% block page_scripts %}{% endblock %}

</footer>
</body>
</html>

crm/web/templates/web/home.html
{% extends 'web/base.html' %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-8">
        CRM Home
    </div>
{% endblock %}

crm/web/templates/web/organizations_form.html
{% extends 'web/base.html' %}
{% load widget_tweaks %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-8">
        <h3>{{ page_title }}</h3>
        <form id="organizationsForm" method="{{ form_method }}" enctype="multipart/form-data" action="{{ form_action }}">
            {% csrf_token %}
            <div class="form-group">
                {% render_field form.name class="form-control" placeholder=form.name.label %}
            </div>
            
            <div class="form-group">
                {% render_field form.province class="form-control" placeholder=form.province.label %}
            </div>

            <div class="form-group">
                {% render_field form.phone_number class="form-control" placeholder=form.phone_number.label %}
            </div>

            <div class="form-group">
                {% render_field form.workers_count class="form-control" placeholder=form.workers_count.label %}
            </div>

            <div class="form-group">
                {% render_field form.contact_fullname class="form-control" placeholder=form.contact_fullname.label %}
            </div>

            <div class="form-group">
                {% render_field form.contact_phone_number class="form-control" placeholder=form.contact_phone_number.label %}
            </div>

            <div class="form-group">
                {% render_field form.email class="form-control" placeholder=form.email.label %}
            </div>

            <div class="form-group">
                {% render_field form.products class="form-control" placeholder=form.products.label %}
            </div>

           
        </form>
        <button id="submitButton" class="btn btn-primary"> Save</button>
    </div>
    <script>
        $('button#submitButton').click( function() {
            var form = $('form#organizationsForm');
            var $crf_token = $('[name="csrfmiddlewaretoken"]').attr('value');

            $.ajax({
                type: form.attr('method'),
                url: form.attr('action'),
                data: form.serialize(),
                headers:{"X-CSRFToken": $crf_token},
                error: 
                    function(data) {
                        alert("ERROR")
                        console.log(data)
                    },
                success: 
                    function(data) {
                        console.log("s")
                        var success_message = 
                            `<div class="alert alert-success alert-dismissible">
                                {{ success_message }}
                                <button type="button" data-dismiss="alert" class="close">&times;</button>
                            </div>`
                        if (form.attr('method') == "POST" ) {
                            $('form#organizationsForm')[0].reset();
                        }
                        $('#messages').append(success_message)
                    },
            });
        });
    </script>
{% endblock %}

crm/web/templates/web/organizations_list.html
{% extends 'web/base.html' %}
{% block page_header_title %}
    {{ page_title }}
{% endblock %}
{% block content %}
    <div class="col-8">
        <h3>{{ page_title }}</h3>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">نام سازمان</th>
                <th scope="col">ثبت کننده</th>
                <th scope="col">مخاطب</th>
                <th scope="col">عملیات</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
    </div>
    <script>

        $( document ).ready(function() {
            $.ajax({
                url: "http://127.0.0.1:8000/organizations/api/",
                headers: {
                    "Accept":"application/json"
                },
                error: 
                    function(data) {
                        alert("ERROR")
                        console.log(data)
                    },
                success: 
                    update_table,
            });
        });
        function update_table(data) {
            for (const organizations_index in data['results']) {
                var organizations = data['results'][organizations_index]
                var row = 
                `<tr>
                    <th scope="row">${Number(organizations_index)+1}</th>
                    <td><a href="/organizations/edit/${organizations['pk']}/">${organizations['name']}</a></td>
                    <td>${organizations['registrar_name']}</td>
                    <td>${organizations['contact_fullname']}</td>
                    <td><a href="#"> ثبت پیگیری </a></td>
                </tr>`
                $("tbody").append(row)
            }
        }
    </script>
{% endblock %}